export const GET_TODOS_REQUEST = "GET_TODOS_REQUEST";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_FAILURE = "GET_TODOS_FAILURE";

export const POST_TODOS_REQUEST = "POST_TODOS_REQUEST";
export const POST_TODO_SUCCESS = "POST_TODO_SUCCESS";
export const POST_TODOS_FAILURE = "POST_TODOS_FAILURE";

export const DELETE_TODOS_REQUEST = "DELETE_TODOS_REQUEST";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODOS_FAILURE = "DELETE_TODOS_FAILURE";

export const PUT_TODOS_REQUEST = "PUT_TODOS_REQUEST";
export const PUT_TODO_SUCCESS = "PUT_TODO_SUCCESS";
export const PUT_TODOS_FAILURE = "PUT_TODOS_FAILURE";

export const TODO_STATUS_CHANGE = "TODO_STATUS_CHANGE";
export const SET_FILTER = "SET_FILTER";